describe("ecs", function()
    local ecs = require("ecs")

    it("should expose core modules", function()
        assert.is_table(ecs.World)
        assert.is_table(ecs.Entity)
        assert.is_table(ecs.ComponentType)
        assert.is_table(ecs.System)
        assert.is_table(ecs.Query)
    end)

    describe("World", function()
        it("should create a world", function()
            local world = ecs.World.new()
            assert.is_table(world)
        end)

        it("should create entities", function()
            local world = ecs.World.new()
            local id1 = world:create_entity()
            local id2 = world:create_entity()
            assert.are.equal(1, id1)
            assert.are.equal(2, id2)
        end)

        it("should destroy entities", function()
            local world = ecs.World.new()
            local id = world:create_entity()
            world:set_component(id, "health", { current = 10 })
            world:destroy_entity(id)
            assert.is_nil(world:get_component(id, "health"))
        end)

        it("should set and get components", function()
            local world = ecs.World.new()
            local id = world:create_entity()
            world:set_component(id, "position", { x = 1, y = 2 })
            local pos = world:get_component(id, "position")
            assert.are.equal(1, pos.x)
            assert.are.equal(2, pos.y)
        end)

        it("should check component existence", function()
            local world = ecs.World.new()
            local id = world:create_entity()
            world:set_component(id, "health", { current = 10 })
            assert.is_true(world:has_component(id, "health"))
            assert.is_false(world:has_component(id, "position"))
        end)

        it("should remove components", function()
            local world = ecs.World.new()
            local id = world:create_entity()
            world:set_component(id, "health", { current = 10 })
            world:remove_component(id, "health")
            assert.is_nil(world:get_component(id, "health"))
        end)

        it("should run registered systems", function()
            local world = ecs.World.new()
            local called = false
            local MySystem = ecs.System.new()
            function MySystem:update(_world, _dt)
                ---@diagnostic disable-next-line: unused-local
                local _w, _d = _world, _dt
                called = true
            end
            world:add_system(MySystem)
            world:update(0.016)
            assert.is_true(called)
        end)
    end)

    describe("Query", function()
        it("should match entities with all components", function()
            local world = ecs.World.new()
            local id1 = world:create_entity()
            local id2 = world:create_entity()
            world:set_component(id1, "position", { x = 0, y = 0 })
            world:set_component(id1, "health", { current = 10 })
            world:set_component(id2, "position", { x = 1, y = 1 })

            local result = ecs.Query.match(world, "position", "health")
            assert.are.equal(1, #result)
            assert.are.equal(id1, result[1])
        end)

        it("should return empty when no components match", function()
            local world = ecs.World.new()
            local result = ecs.Query.match(world, "missing")
            assert.are.equal(0, #result)
        end)
    end)

    describe("ComponentType", function()
        it("should create component instances with defaults", function()
            local HealthType = ecs.ComponentType.new("health", { current = 10, maximum = 10 })
            local instance = HealthType:create()
            assert.are.equal(10, instance.current)
            assert.are.equal(10, instance.maximum)
        end)
    end)
end)
