describe("entity", function()
    it("should load the entity module", function()
        local entity = require("entity")
        assert.is_table(entity)
    end)

    it("should create a health component", function()
        local Health = require("entity.components.health")
        local health = Health.new(5, 10)
        assert.are.equal(5, health.current)
        assert.are.equal(10, health.maximum)
    end)

    it("should create an inventory component", function()
        local Inventory = require("entity.components.inventory")
        local inv = Inventory.new()
        assert.is_table(inv.items)
    end)

    it("should create a combat system", function()
        local Combat = require("entity.systems.combat")
        local system = Combat.new()
        assert.is_table(system)
    end)
end)
