describe("world", function()
    it("should load the world module", function()
        local world = require("world")
        assert.is_table(world)
    end)

    it("should create a position component", function()
        local Position = require("world.components.position")
        local pos = Position.new(1, 2)
        assert.are.equal(1, pos.x)
        assert.are.equal(2, pos.y)
    end)

    it("should create a movement system", function()
        local Movement = require("world.systems.movement")
        local system = Movement.new()
        assert.is_table(system)
    end)
end)
